## dialogue change
execute @s[scores={phase=0}] ~ ~ ~ dialogue change @e[tag=friend] friend1
execute @s[scores={teacher=1}] ~ ~ ~ dialogue change @e[tag=teacher] teacher1
execute @s[scores={teacher=2}] ~ ~ ~ dialogue change @e[tag=teacher] teacher2
execute @s[scores={teacher=3}] ~ ~ ~ dialogue change @e[tag=teacher] teacher4
execute @s[scores={jan=1}] ~ ~ ~ dialogue change @e[tag=jan] jan1
execute @s[scores={jan=2}] ~ ~ ~ dialogue change @e[tag=jan] jan2
execute @s[scores={jan=3}] ~ ~ ~ dialogue change @e[tag=jan] jan3
execute @s[scores={jan=4}] ~ ~ ~ dialogue change @e[tag=jan] jan4
execute @s[scores={jan=5}] ~ ~ ~ dialogue change @e[tag=jan] jan5
execute @s[scores={guide=1}] ~ ~ ~ dialogue change @e[tag=guide] guide1
execute @s[scores={guide=2}] ~ ~ ~ dialogue change @e[tag=guide] guide6
execute @s[scores={guide=3}] ~ ~ ~ dialogue change @e[tag=guide] guide8
execute @s[scores={mayor=1}] ~ ~ ~ dialogue change @e[tag=mayor] mayor1
execute @s[scores={mayor=2}] ~ ~ ~ dialogue change @e[tag=mayor] mayor1
execute @s[scores={mayor=3}] ~ ~ ~ dialogue change @e[tag=mayor] mayor3
execute @s[scores={mayor=4}] ~ ~ ~ dialogue change @e[tag=mayor] mayor7
execute @s[scores={mayor=5}] ~ ~ ~ dialogue change @e[tag=mayor] mayor8
execute @s[scores={mayor=1}] ~ ~ ~ dialogue change @e[tag=secretary] secretary1
execute @s[scores={mayor=2}] ~ ~ ~ dialogue change @e[tag=secretary] secretary2
execute @s ~ ~ ~ dialogue change @e[tag=barbara] barbara1
execute @s ~ ~ ~ dialogue change @e[tag=dustin] dustin1
execute @s ~ ~ ~ dialogue change @e[tag=flavor1] flavor11
execute @s ~ ~ ~ dialogue change @e[tag=flavor2] flavor21
execute @s ~ ~ ~ dialogue change @e[tag=flavor3] flavor31
execute @s ~ ~ ~ dialogue change @e[tag=maxine] maxine1
execute @s ~ ~ ~ dialogue change @e[tag=mike] mike1
execute @s[scores={jan=1}] ~ ~ ~ dialogue change @e[tag=npc1] npc11
execute @s[scores={jan=2}] ~ ~ ~ dialogue change @e[tag=npc2] npc21
execute @s ~ ~ ~ dialogue change @e[tag=intro] intro1